# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.setEnabled(True)
        Widget.resize(800, 600)
        self.pushButton = QPushButton(Widget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QRect(205, 10, 51, 481))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton_2 = QPushButton(Widget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(260, 10, 51, 481))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_3 = QPushButton(Widget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QRect(315, 10, 51, 481))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_4 = QPushButton(Widget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QRect(370, 20, 51, 471))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_5 = QPushButton(Widget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QRect(425, 20, 51, 471))
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_6 = QPushButton(Widget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QRect(480, 20, 51, 471))
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_7 = QPushButton(Widget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QRect(535, 30, 51, 461))
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setAutoDefault(False)
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 120, 415, 381))
        self.label.setPixmap(QPixmap(u"../images/connect panal 2.PNG"))
        self.gridLayoutWidget = QWidget(Widget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(160, 140, 141, 341))
        self.gridLayout_70 = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_70.setSpacing(0)
        self.gridLayout_70.setObjectName(u"gridLayout_70")
        self.gridLayout_70.setContentsMargins(0, 0, 0, 0)
        self.label_2_0 = QLabel(self.gridLayoutWidget)
        self.label_2_0.setObjectName(u"label_2_0")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2_0.sizePolicy().hasHeightForWidth())
        self.label_2_0.setSizePolicy(sizePolicy)
        self.label_2_0.setMinimumSize(QSize(0, 0))
        self.label_2_0.setMaximumSize(QSize(51, 51))

        self.gridLayout_70.addWidget(self.label_2_0, 3, 0, 1, 1)

        self.label_3_0 = QLabel(self.gridLayoutWidget)
        self.label_3_0.setObjectName(u"label_3_0")
        sizePolicy.setHeightForWidth(self.label_3_0.sizePolicy().hasHeightForWidth())
        self.label_3_0.setSizePolicy(sizePolicy)
        self.label_3_0.setMinimumSize(QSize(0, 0))
        self.label_3_0.setMaximumSize(QSize(51, 51))

        self.gridLayout_70.addWidget(self.label_3_0, 4, 0, 1, 1)

        self.label_1_0 = QLabel(self.gridLayoutWidget)
        self.label_1_0.setObjectName(u"label_1_0")
        sizePolicy.setHeightForWidth(self.label_1_0.sizePolicy().hasHeightForWidth())
        self.label_1_0.setSizePolicy(sizePolicy)
        self.label_1_0.setMinimumSize(QSize(0, 0))
        self.label_1_0.setMaximumSize(QSize(51, 51))

        self.gridLayout_70.addWidget(self.label_1_0, 2, 0, 1, 1)

        self.label_5_0 = QLabel(self.gridLayoutWidget)
        self.label_5_0.setObjectName(u"label_5_0")
        sizePolicy.setHeightForWidth(self.label_5_0.sizePolicy().hasHeightForWidth())
        self.label_5_0.setSizePolicy(sizePolicy)
        self.label_5_0.setMinimumSize(QSize(0, 0))
        self.label_5_0.setMaximumSize(QSize(51, 51))

        self.gridLayout_70.addWidget(self.label_5_0, 6, 0, 1, 1)

        self.label_4_0 = QLabel(self.gridLayoutWidget)
        self.label_4_0.setObjectName(u"label_4_0")
        sizePolicy.setHeightForWidth(self.label_4_0.sizePolicy().hasHeightForWidth())
        self.label_4_0.setSizePolicy(sizePolicy)
        self.label_4_0.setMinimumSize(QSize(0, 0))
        self.label_4_0.setMaximumSize(QSize(51, 51))

        self.gridLayout_70.addWidget(self.label_4_0, 5, 0, 1, 1)

        self.label_0_0 = QLabel(self.gridLayoutWidget)
        self.label_0_0.setObjectName(u"label_0_0")
        sizePolicy.setHeightForWidth(self.label_0_0.sizePolicy().hasHeightForWidth())
        self.label_0_0.setSizePolicy(sizePolicy)
        self.label_0_0.setMinimumSize(QSize(0, 0))
        self.label_0_0.setMaximumSize(QSize(51, 51))

        self.gridLayout_70.addWidget(self.label_0_0, 1, 0, 1, 1)

        self.gridLayoutWidget_2 = QWidget(Widget)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(270, 140, 141, 341))
        self.gridLayout_72 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_72.setSpacing(0)
        self.gridLayout_72.setObjectName(u"gridLayout_72")
        self.gridLayout_72.setContentsMargins(0, 0, 0, 0)
        self.label_1_4 = QLabel(self.gridLayoutWidget_2)
        self.label_1_4.setObjectName(u"label_1_4")
        sizePolicy.setHeightForWidth(self.label_1_4.sizePolicy().hasHeightForWidth())
        self.label_1_4.setSizePolicy(sizePolicy)
        self.label_1_4.setMinimumSize(QSize(0, 0))
        self.label_1_4.setMaximumSize(QSize(51, 51))

        self.gridLayout_72.addWidget(self.label_1_4, 2, 0, 1, 1)

        self.label_2_4 = QLabel(self.gridLayoutWidget_2)
        self.label_2_4.setObjectName(u"label_2_4")
        sizePolicy.setHeightForWidth(self.label_2_4.sizePolicy().hasHeightForWidth())
        self.label_2_4.setSizePolicy(sizePolicy)
        self.label_2_4.setMinimumSize(QSize(0, 0))
        self.label_2_4.setMaximumSize(QSize(51, 51))

        self.gridLayout_72.addWidget(self.label_2_4, 3, 0, 1, 1)

        self.label_4_4 = QLabel(self.gridLayoutWidget_2)
        self.label_4_4.setObjectName(u"label_4_4")
        sizePolicy.setHeightForWidth(self.label_4_4.sizePolicy().hasHeightForWidth())
        self.label_4_4.setSizePolicy(sizePolicy)
        self.label_4_4.setMinimumSize(QSize(0, 0))
        self.label_4_4.setMaximumSize(QSize(51, 51))

        self.gridLayout_72.addWidget(self.label_4_4, 5, 0, 1, 1)

        self.label_5_4 = QLabel(self.gridLayoutWidget_2)
        self.label_5_4.setObjectName(u"label_5_4")
        sizePolicy.setHeightForWidth(self.label_5_4.sizePolicy().hasHeightForWidth())
        self.label_5_4.setSizePolicy(sizePolicy)
        self.label_5_4.setMinimumSize(QSize(0, 0))
        self.label_5_4.setMaximumSize(QSize(51, 51))

        self.gridLayout_72.addWidget(self.label_5_4, 6, 0, 1, 1)

        self.label_3_4 = QLabel(self.gridLayoutWidget_2)
        self.label_3_4.setObjectName(u"label_3_4")
        sizePolicy.setHeightForWidth(self.label_3_4.sizePolicy().hasHeightForWidth())
        self.label_3_4.setSizePolicy(sizePolicy)
        self.label_3_4.setMinimumSize(QSize(0, 0))
        self.label_3_4.setMaximumSize(QSize(51, 51))

        self.gridLayout_72.addWidget(self.label_3_4, 4, 0, 1, 1)

        self.label_0_4 = QLabel(self.gridLayoutWidget_2)
        self.label_0_4.setObjectName(u"label_0_4")
        sizePolicy.setHeightForWidth(self.label_0_4.sizePolicy().hasHeightForWidth())
        self.label_0_4.setSizePolicy(sizePolicy)
        self.label_0_4.setMinimumSize(QSize(0, 0))
        self.label_0_4.setMaximumSize(QSize(51, 51))

        self.gridLayout_72.addWidget(self.label_0_4, 1, 0, 1, 1)

        self.gridLayoutWidget_3 = QWidget(Widget)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(380, 140, 141, 341))
        self.gridLayout_74 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_74.setSpacing(0)
        self.gridLayout_74.setObjectName(u"gridLayout_74")
        self.gridLayout_74.setContentsMargins(0, 0, 0, 0)
        self.label_0_8 = QLabel(self.gridLayoutWidget_3)
        self.label_0_8.setObjectName(u"label_0_8")
        sizePolicy.setHeightForWidth(self.label_0_8.sizePolicy().hasHeightForWidth())
        self.label_0_8.setSizePolicy(sizePolicy)
        self.label_0_8.setMinimumSize(QSize(0, 0))
        self.label_0_8.setMaximumSize(QSize(51, 51))

        self.gridLayout_74.addWidget(self.label_0_8, 1, 0, 1, 1)

        self.label_2_8 = QLabel(self.gridLayoutWidget_3)
        self.label_2_8.setObjectName(u"label_2_8")
        sizePolicy.setHeightForWidth(self.label_2_8.sizePolicy().hasHeightForWidth())
        self.label_2_8.setSizePolicy(sizePolicy)
        self.label_2_8.setMinimumSize(QSize(0, 0))
        self.label_2_8.setMaximumSize(QSize(51, 51))

        self.gridLayout_74.addWidget(self.label_2_8, 3, 0, 1, 1)

        self.label_4_8 = QLabel(self.gridLayoutWidget_3)
        self.label_4_8.setObjectName(u"label_4_8")
        sizePolicy.setHeightForWidth(self.label_4_8.sizePolicy().hasHeightForWidth())
        self.label_4_8.setSizePolicy(sizePolicy)
        self.label_4_8.setMinimumSize(QSize(0, 0))
        self.label_4_8.setMaximumSize(QSize(51, 51))

        self.gridLayout_74.addWidget(self.label_4_8, 5, 0, 1, 1)

        self.label_5_8 = QLabel(self.gridLayoutWidget_3)
        self.label_5_8.setObjectName(u"label_5_8")
        sizePolicy.setHeightForWidth(self.label_5_8.sizePolicy().hasHeightForWidth())
        self.label_5_8.setSizePolicy(sizePolicy)
        self.label_5_8.setMinimumSize(QSize(0, 0))
        self.label_5_8.setMaximumSize(QSize(51, 51))

        self.gridLayout_74.addWidget(self.label_5_8, 6, 0, 1, 1)

        self.label_1_8 = QLabel(self.gridLayoutWidget_3)
        self.label_1_8.setObjectName(u"label_1_8")
        sizePolicy.setHeightForWidth(self.label_1_8.sizePolicy().hasHeightForWidth())
        self.label_1_8.setSizePolicy(sizePolicy)
        self.label_1_8.setMinimumSize(QSize(0, 0))
        self.label_1_8.setMaximumSize(QSize(51, 51))

        self.gridLayout_74.addWidget(self.label_1_8, 2, 0, 1, 1)

        self.label_3_8 = QLabel(self.gridLayoutWidget_3)
        self.label_3_8.setObjectName(u"label_3_8")
        sizePolicy.setHeightForWidth(self.label_3_8.sizePolicy().hasHeightForWidth())
        self.label_3_8.setSizePolicy(sizePolicy)
        self.label_3_8.setMinimumSize(QSize(0, 0))
        self.label_3_8.setMaximumSize(QSize(51, 51))

        self.gridLayout_74.addWidget(self.label_3_8, 4, 0, 1, 1)

        self.gridLayoutWidget_4 = QWidget(Widget)
        self.gridLayoutWidget_4.setObjectName(u"gridLayoutWidget_4")
        self.gridLayoutWidget_4.setGeometry(QRect(490, 140, 141, 341))
        self.gridLayout_76 = QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_76.setSpacing(0)
        self.gridLayout_76.setObjectName(u"gridLayout_76")
        self.gridLayout_76.setContentsMargins(0, 0, 0, 0)
        self.label_2_12 = QLabel(self.gridLayoutWidget_4)
        self.label_2_12.setObjectName(u"label_2_12")
        sizePolicy.setHeightForWidth(self.label_2_12.sizePolicy().hasHeightForWidth())
        self.label_2_12.setSizePolicy(sizePolicy)
        self.label_2_12.setMinimumSize(QSize(0, 0))
        self.label_2_12.setMaximumSize(QSize(51, 51))

        self.gridLayout_76.addWidget(self.label_2_12, 3, 0, 1, 1)

        self.label_4_12 = QLabel(self.gridLayoutWidget_4)
        self.label_4_12.setObjectName(u"label_4_12")
        sizePolicy.setHeightForWidth(self.label_4_12.sizePolicy().hasHeightForWidth())
        self.label_4_12.setSizePolicy(sizePolicy)
        self.label_4_12.setMinimumSize(QSize(0, 0))
        self.label_4_12.setMaximumSize(QSize(51, 51))

        self.gridLayout_76.addWidget(self.label_4_12, 5, 0, 1, 1)

        self.label_3_12 = QLabel(self.gridLayoutWidget_4)
        self.label_3_12.setObjectName(u"label_3_12")
        sizePolicy.setHeightForWidth(self.label_3_12.sizePolicy().hasHeightForWidth())
        self.label_3_12.setSizePolicy(sizePolicy)
        self.label_3_12.setMinimumSize(QSize(0, 0))
        self.label_3_12.setMaximumSize(QSize(51, 51))

        self.gridLayout_76.addWidget(self.label_3_12, 4, 0, 1, 1)

        self.label_1_12 = QLabel(self.gridLayoutWidget_4)
        self.label_1_12.setObjectName(u"label_1_12")
        sizePolicy.setHeightForWidth(self.label_1_12.sizePolicy().hasHeightForWidth())
        self.label_1_12.setSizePolicy(sizePolicy)
        self.label_1_12.setMinimumSize(QSize(0, 0))
        self.label_1_12.setMaximumSize(QSize(51, 51))

        self.gridLayout_76.addWidget(self.label_1_12, 2, 0, 1, 1)

        self.label_0_12 = QLabel(self.gridLayoutWidget_4)
        self.label_0_12.setObjectName(u"label_0_12")
        sizePolicy.setHeightForWidth(self.label_0_12.sizePolicy().hasHeightForWidth())
        self.label_0_12.setSizePolicy(sizePolicy)
        self.label_0_12.setMinimumSize(QSize(0, 0))
        self.label_0_12.setMaximumSize(QSize(51, 51))

        self.gridLayout_76.addWidget(self.label_0_12, 1, 0, 1, 1)

        self.label_5_12 = QLabel(self.gridLayoutWidget_4)
        self.label_5_12.setObjectName(u"label_5_12")
        sizePolicy.setHeightForWidth(self.label_5_12.sizePolicy().hasHeightForWidth())
        self.label_5_12.setSizePolicy(sizePolicy)
        self.label_5_12.setMinimumSize(QSize(0, 0))
        self.label_5_12.setMaximumSize(QSize(51, 51))

        self.gridLayout_76.addWidget(self.label_5_12, 6, 0, 1, 1)

        self.gridLayoutWidget_8 = QWidget(Widget)
        self.gridLayoutWidget_8.setObjectName(u"gridLayoutWidget_8")
        self.gridLayoutWidget_8.setGeometry(QRect(210, 140, 151, 341))
        self.gridLayout_71 = QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_71.setSpacing(0)
        self.gridLayout_71.setObjectName(u"gridLayout_71")
        self.gridLayout_71.setContentsMargins(0, 0, 0, 0)
        self.label_2_2 = QLabel(self.gridLayoutWidget_8)
        self.label_2_2.setObjectName(u"label_2_2")
        sizePolicy.setHeightForWidth(self.label_2_2.sizePolicy().hasHeightForWidth())
        self.label_2_2.setSizePolicy(sizePolicy)
        self.label_2_2.setMinimumSize(QSize(0, 0))
        self.label_2_2.setMaximumSize(QSize(51, 51))

        self.gridLayout_71.addWidget(self.label_2_2, 3, 0, 1, 1)

        self.label_3_2 = QLabel(self.gridLayoutWidget_8)
        self.label_3_2.setObjectName(u"label_3_2")
        sizePolicy.setHeightForWidth(self.label_3_2.sizePolicy().hasHeightForWidth())
        self.label_3_2.setSizePolicy(sizePolicy)
        self.label_3_2.setMinimumSize(QSize(0, 0))
        self.label_3_2.setMaximumSize(QSize(51, 51))

        self.gridLayout_71.addWidget(self.label_3_2, 4, 0, 1, 1)

        self.label_1_2 = QLabel(self.gridLayoutWidget_8)
        self.label_1_2.setObjectName(u"label_1_2")
        sizePolicy.setHeightForWidth(self.label_1_2.sizePolicy().hasHeightForWidth())
        self.label_1_2.setSizePolicy(sizePolicy)
        self.label_1_2.setMinimumSize(QSize(0, 0))
        self.label_1_2.setMaximumSize(QSize(51, 51))

        self.gridLayout_71.addWidget(self.label_1_2, 2, 0, 1, 1)

        self.label_5_2 = QLabel(self.gridLayoutWidget_8)
        self.label_5_2.setObjectName(u"label_5_2")
        sizePolicy.setHeightForWidth(self.label_5_2.sizePolicy().hasHeightForWidth())
        self.label_5_2.setSizePolicy(sizePolicy)
        self.label_5_2.setMinimumSize(QSize(0, 0))
        self.label_5_2.setMaximumSize(QSize(51, 51))

        self.gridLayout_71.addWidget(self.label_5_2, 6, 0, 1, 1)

        self.label_4_2 = QLabel(self.gridLayoutWidget_8)
        self.label_4_2.setObjectName(u"label_4_2")
        sizePolicy.setHeightForWidth(self.label_4_2.sizePolicy().hasHeightForWidth())
        self.label_4_2.setSizePolicy(sizePolicy)
        self.label_4_2.setMinimumSize(QSize(0, 0))
        self.label_4_2.setMaximumSize(QSize(51, 51))

        self.gridLayout_71.addWidget(self.label_4_2, 5, 0, 1, 1)

        self.label_0_2 = QLabel(self.gridLayoutWidget_8)
        self.label_0_2.setObjectName(u"label_0_2")
        sizePolicy.setHeightForWidth(self.label_0_2.sizePolicy().hasHeightForWidth())
        self.label_0_2.setSizePolicy(sizePolicy)
        self.label_0_2.setMinimumSize(QSize(0, 0))
        self.label_0_2.setMaximumSize(QSize(51, 51))

        self.gridLayout_71.addWidget(self.label_0_2, 1, 0, 1, 1)

        self.gridLayoutWidget_9 = QWidget(Widget)
        self.gridLayoutWidget_9.setObjectName(u"gridLayoutWidget_9")
        self.gridLayoutWidget_9.setGeometry(QRect(320, 140, 151, 341))
        self.gridLayout_73 = QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_73.setSpacing(0)
        self.gridLayout_73.setObjectName(u"gridLayout_73")
        self.gridLayout_73.setContentsMargins(0, 0, 0, 0)
        self.label_2_6 = QLabel(self.gridLayoutWidget_9)
        self.label_2_6.setObjectName(u"label_2_6")
        sizePolicy.setHeightForWidth(self.label_2_6.sizePolicy().hasHeightForWidth())
        self.label_2_6.setSizePolicy(sizePolicy)
        self.label_2_6.setMinimumSize(QSize(0, 0))
        self.label_2_6.setMaximumSize(QSize(51, 51))

        self.gridLayout_73.addWidget(self.label_2_6, 3, 0, 1, 1)

        self.label_3_6 = QLabel(self.gridLayoutWidget_9)
        self.label_3_6.setObjectName(u"label_3_6")
        sizePolicy.setHeightForWidth(self.label_3_6.sizePolicy().hasHeightForWidth())
        self.label_3_6.setSizePolicy(sizePolicy)
        self.label_3_6.setMinimumSize(QSize(0, 0))
        self.label_3_6.setMaximumSize(QSize(51, 51))

        self.gridLayout_73.addWidget(self.label_3_6, 4, 0, 1, 1)

        self.label_1_6 = QLabel(self.gridLayoutWidget_9)
        self.label_1_6.setObjectName(u"label_1_6")
        sizePolicy.setHeightForWidth(self.label_1_6.sizePolicy().hasHeightForWidth())
        self.label_1_6.setSizePolicy(sizePolicy)
        self.label_1_6.setMinimumSize(QSize(0, 0))
        self.label_1_6.setMaximumSize(QSize(51, 51))

        self.gridLayout_73.addWidget(self.label_1_6, 2, 0, 1, 1)

        self.label_5_6 = QLabel(self.gridLayoutWidget_9)
        self.label_5_6.setObjectName(u"label_5_6")
        sizePolicy.setHeightForWidth(self.label_5_6.sizePolicy().hasHeightForWidth())
        self.label_5_6.setSizePolicy(sizePolicy)
        self.label_5_6.setMinimumSize(QSize(0, 0))
        self.label_5_6.setMaximumSize(QSize(51, 51))

        self.gridLayout_73.addWidget(self.label_5_6, 6, 0, 1, 1)

        self.label_4_6 = QLabel(self.gridLayoutWidget_9)
        self.label_4_6.setObjectName(u"label_4_6")
        sizePolicy.setHeightForWidth(self.label_4_6.sizePolicy().hasHeightForWidth())
        self.label_4_6.setSizePolicy(sizePolicy)
        self.label_4_6.setMinimumSize(QSize(0, 0))
        self.label_4_6.setMaximumSize(QSize(51, 51))

        self.gridLayout_73.addWidget(self.label_4_6, 5, 0, 1, 1)

        self.label_0_6 = QLabel(self.gridLayoutWidget_9)
        self.label_0_6.setObjectName(u"label_0_6")
        sizePolicy.setHeightForWidth(self.label_0_6.sizePolicy().hasHeightForWidth())
        self.label_0_6.setSizePolicy(sizePolicy)
        self.label_0_6.setMinimumSize(QSize(0, 0))
        self.label_0_6.setMaximumSize(QSize(51, 51))

        self.gridLayout_73.addWidget(self.label_0_6, 1, 0, 1, 1)

        self.gridLayoutWidget_10 = QWidget(Widget)
        self.gridLayoutWidget_10.setObjectName(u"gridLayoutWidget_10")
        self.gridLayoutWidget_10.setGeometry(QRect(430, 140, 151, 341))
        self.gridLayout_75 = QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_75.setSpacing(0)
        self.gridLayout_75.setObjectName(u"gridLayout_75")
        self.gridLayout_75.setContentsMargins(0, 0, 0, 0)
        self.label_2_10 = QLabel(self.gridLayoutWidget_10)
        self.label_2_10.setObjectName(u"label_2_10")
        sizePolicy.setHeightForWidth(self.label_2_10.sizePolicy().hasHeightForWidth())
        self.label_2_10.setSizePolicy(sizePolicy)
        self.label_2_10.setMinimumSize(QSize(0, 0))
        self.label_2_10.setMaximumSize(QSize(51, 51))

        self.gridLayout_75.addWidget(self.label_2_10, 3, 0, 1, 1)

        self.label_3_10 = QLabel(self.gridLayoutWidget_10)
        self.label_3_10.setObjectName(u"label_3_10")
        sizePolicy.setHeightForWidth(self.label_3_10.sizePolicy().hasHeightForWidth())
        self.label_3_10.setSizePolicy(sizePolicy)
        self.label_3_10.setMinimumSize(QSize(0, 0))
        self.label_3_10.setMaximumSize(QSize(51, 51))

        self.gridLayout_75.addWidget(self.label_3_10, 4, 0, 1, 1)

        self.label_1_10 = QLabel(self.gridLayoutWidget_10)
        self.label_1_10.setObjectName(u"label_1_10")
        sizePolicy.setHeightForWidth(self.label_1_10.sizePolicy().hasHeightForWidth())
        self.label_1_10.setSizePolicy(sizePolicy)
        self.label_1_10.setMinimumSize(QSize(0, 0))
        self.label_1_10.setMaximumSize(QSize(51, 51))

        self.gridLayout_75.addWidget(self.label_1_10, 2, 0, 1, 1)

        self.label_5_10 = QLabel(self.gridLayoutWidget_10)
        self.label_5_10.setObjectName(u"label_5_10")
        sizePolicy.setHeightForWidth(self.label_5_10.sizePolicy().hasHeightForWidth())
        self.label_5_10.setSizePolicy(sizePolicy)
        self.label_5_10.setMinimumSize(QSize(0, 0))
        self.label_5_10.setMaximumSize(QSize(51, 51))

        self.gridLayout_75.addWidget(self.label_5_10, 6, 0, 1, 1)

        self.label_4_10 = QLabel(self.gridLayoutWidget_10)
        self.label_4_10.setObjectName(u"label_4_10")
        sizePolicy.setHeightForWidth(self.label_4_10.sizePolicy().hasHeightForWidth())
        self.label_4_10.setSizePolicy(sizePolicy)
        self.label_4_10.setMinimumSize(QSize(0, 0))
        self.label_4_10.setMaximumSize(QSize(51, 51))

        self.gridLayout_75.addWidget(self.label_4_10, 5, 0, 1, 1)

        self.label_0_10 = QLabel(self.gridLayoutWidget_10)
        self.label_0_10.setObjectName(u"label_0_10")
        sizePolicy.setHeightForWidth(self.label_0_10.sizePolicy().hasHeightForWidth())
        self.label_0_10.setSizePolicy(sizePolicy)
        self.label_0_10.setMinimumSize(QSize(0, 0))
        self.label_0_10.setMaximumSize(QSize(51, 51))

        self.gridLayout_75.addWidget(self.label_0_10, 1, 0, 1, 1)

        

        self.pushButton.setVisible(0)
        self.pushButton_2.setVisible(0)
        self.pushButton_3.setVisible(0)
        self.pushButton_4.setVisible(0)
        self.pushButton_5.setVisible(0)
        self.pushButton_6.setVisible(0)
        self.pushButton_7.setVisible(0)

        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_2.raise_()
        self.pushButton_7.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.gridLayoutWidget_3.raise_()
        self.gridLayoutWidget_4.raise_()
        self.gridLayoutWidget_8.raise_()
        self.gridLayoutWidget_9.raise_()
        self.gridLayoutWidget_10.raise_()
        self.label.raise_()

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
#if QT_CONFIG(tooltip)
        self.pushButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pushButton.setText("")
        self.pushButton_2.setText("")
        self.pushButton_3.setText("")
        self.pushButton_4.setText("")
        self.pushButton_5.setText("")
        self.pushButton_6.setText("")
        self.pushButton_7.setText("")
        self.label.setText("")
        self.label_2_0.setText("")
        self.label_3_0.setText("")
        self.label_1_0.setText("")
        self.label_5_0.setText("")
        self.label_4_0.setText("")
        self.label_0_0.setText("")
        self.label_1_4.setText("")
        self.label_2_4.setText("")
        self.label_4_4.setText("")
        self.label_5_4.setText("")
        self.label_3_4.setText("")
        self.label_0_4.setText("")
        self.label_0_8.setText("")
        self.label_2_8.setText("")
        self.label_4_8.setText("")
        self.label_5_8.setText("")
        self.label_1_8.setText("")
        self.label_3_8.setText("")
        self.label_2_12.setText("")
        self.label_4_12.setText("")
        self.label_3_12.setText("")
        self.label_1_12.setText("")
        self.label_0_12.setText("")
        self.label_5_12.setText("")
        self.label_2_2.setText("")
        self.label_3_2.setText("")
        self.label_1_2.setText("")
        self.label_5_2.setText("")
        self.label_4_2.setText("")
        self.label_0_2.setText("")
        self.label_2_6.setText("")
        self.label_3_6.setText("")
        self.label_1_6.setText("")
        self.label_5_6.setText("")
        self.label_4_6.setText("")
        self.label_0_6.setText("")
        self.label_2_10.setText("")
        self.label_3_10.setText("")
        self.label_1_10.setText("")
        self.label_5_10.setText("")
        self.label_4_10.setText("")
        self.label_0_10.setText("")
    # retranslateUi

